
[turtlePeripherals]
	enableCreativeChest = true
	enableTurtleChatter = true

[operations]
	#Range: > 0
	smeltCost = 80
	#Range: > 1000
	useCooldown = 5000
	#Range: > 0
	chiselCost = 1
	#Range: > 1000
	transformBlockCooldown = 1000
	#Range: > 1000
	xpTransferCooldown = 1000
	#Range: 1 ~ 64
	scanBlocksMaxFreeRadius = 8
	#Range: > 0
	warpCost = 1
	#Range: > 0
	useCost = 1
	#Range: 1 ~ 64
	scanEntitiesMaxFreeRadius = 8
	#Range: 0.1 ~ 1.7976931348623157E308
	scanEntitiesExtraBlockCost = 0.17
	#Range: > 1000
	smeltCooldown = 1000
	#Range: > 0
	captureCost = 100
	#Range: > 1000
	chatMessageCooldown = 1000
	#Range: > 0
	transformBlockCost = 1
	#Range: > 1000
	scanBlocksCooldown = 2000
	#Range: 1 ~ 64
	scanEntitiesMaxCostRadius = 16
	#Range: > 1000
	smithCooldown = 1000
	#Range: > 1000
	brewCooldown = 1000
	#Range: > 0
	suckCost = 1
	#Range: > 0
	throwPotionCost = 10
	#Range: > 1000
	enchantmentCooldown = 5000
	#Range: > 1000
	swingCooldown = 1000
	#Range: > 0
	smithCost = 1
	#Range: > 1000
	scanEntitiesCooldown = 2000
	#Range: > 1000
	captureCooldown = 50000
	#Range: 0.1 ~ 1.7976931348623157E308
	scanBlocksExtraBlockCost = 0.17
	#Range: > 0
	brewCost = 5
	#Range: > 0
	swingCost = 1
	#Range: > 1000
	suckCooldown = 1000
	#Range: > 1000
	throwPotionCooldown = 1000
	#Range: > 0
	xpTransferCost = 1
	#Range: 1 ~ 64
	scanBlocksMaxCostRadius = 16
	#Range: > 0
	enchantmentCost = 10
	#Range: > 1000
	warpCooldown = 1000
	#Range: > 1000
	chiselCooldown = 1000

[automataCores]
	#Range: 0.1 ~ 1.0
	enchantmentWipeChance = 0.1
	#Range: 1 ~ 32
	tier3AutomataCoreMaxFuelConsumptionRate = 4
	enableBrewingAutomataCore = true
	#Range: 1 ~ 64
	tier2AutomataCoreInteractionRadius = 4
	#Range: 1 ~ 32
	tier2AutomataCoreMaxFuelConsumptionRate = 3
	enableWeakAutomataCore = true
	enableEnormousAutomata = true
	#Range: 1 ~ 32
	enormousTierAutomataCoreMaxFuelConsumptionRate = 32
	#Range: 1 ~ 64
	tier1AutomataCoreInteractionRadius = 2
	#Range: 1 ~ 32
	tier1AutomataCoreMaxFuelConsumptionRate = 2
	enableHusbandryAutomataCore = true
	enableEnchantingAutomataCore = true
	enableMasonAutomataCore = true
	#Range: 1 ~ 64
	tier3AutomataCoreInteractionRadius = 8
	enableSmithingAutomataCore = true
	#Range: > 1
	enchantLevelCost = 30
	#Range: 1 ~ 64
	enormousTierAutomataCoreInteractionRadius = 64
	#Defines max warp point stored in warp core. Mostly need to not allow NBT overflow error
	#Range: > 1
	endAutomataCoreWarpPointLimit = 64
	#Range: 0.0 ~ 64.0
	brewingXPReward = 0.8
	enableEndAutomataCore = true

